logging:
  level:
    com.board.board: debug
    #    request /response 정보 볼수있다.
#    org.springframework.web.servlet: debug
    #    쿼리로그를 디버그모드로 볼수있고 '?' 파라미터를 볼수있다.
    org.hibernate.orm.jdbc.bind: trace
spring:
  profiles:
    active: local
  datasource:
#    url: jdbc:mysql://localhost:3306/inflearn
    url: jdbc:mysql://host.docker.internal:3306/inflearn
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #    스프링부트 2.4~5부터 생김, true로 하면 테스트용 데이터를 넣을수있게끔 가능해짐 (/resources/xxx.sql)
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # 한줄로 나와야되는 디버깅쿼리문을 예쁘게 포맷해서 보여줌
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  data:
    redis:
      host: host.docker.internal
#      host: localhost
      port: 6379

# 액추에이터에서 톰캣 스레드 보는 설정 추가 -> 프로테메우스로 전달
server:
  tomcat:
    mbeanregistry:
      enabled: true

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml

# 프로메테우스 설정
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
